"""
Gaussian Mixture Model (GMM) clustering.

Models the data as a mixture of k multivariate Gaussian distributions fitted via
Expectation-Maximisation. Each point receives a soft probabilistic assignment; the
hard label is the component with the highest posterior. When k is not given it is
chosen by minimising the Bayesian Information Criterion (BIC).

Pros:
  - Soft assignments capture uncertainty; points near cluster boundaries get split
    probability rather than an arbitrary hard assignment.
  - Flexible covariance (full, tied, diagonal, spherical) allows elongated clusters.
  - BIC-based auto-detection is more principled than K-Means elbow heuristic.

Cons:
  - Assumes data is generated by Gaussian components — fails when clusters are not
    roughly ellipsoidal (e.g. ring-shaped or manifold data).
  - EM can converge to local optima; results vary without a fixed random_state.
  - Full covariance requires O(d²) parameters per component — expensive in high dimensions.
  - BIC auto-detection still requires fitting k models up to max_clusters.
"""

from sklearn.mixture import GaussianMixture
import numpy as np

from src.abstractions import ClusteringBase, ImageData


class GMMClusterer(ClusteringBase):
    def cluster(self, images: list[ImageData], **kwargs) -> list[int]:
        n_components = kwargs.get("n_clusters")
        covariance_type = kwargs.get("covariance_type", "full")
        random_state = kwargs.get("random_state", 0)
        embeddings = np.array([img.embedding for img in images])

        if n_components is None:
            max_k = min(len(embeddings), kwargs.get("max_clusters", 20))
            if max_k < 2:
                n_components = 1
            else:
                # Start at k=2 (not 1): with a single component every point gets
                # the same label, which collapses the clustering to one cluster
                # and leaves silhouette / Calinski-Harabasz / Davies-Bouldin
                # undefined (they require >1 cluster). BIC's complexity penalty
                # otherwise favours k=1 on high-dim embeddings, so the run would
                # report no intrinsic metrics. Mirrors KMeans' elbow search.
                ks = range(2, max_k + 1)
                bics = [
                    GaussianMixture(n_components=k, covariance_type=covariance_type, random_state=random_state).fit(embeddings).bic(embeddings)
                    for k in ks
                ]
                n_components = ks[int(np.argmin(bics))]

        gmm = GaussianMixture(n_components=n_components, covariance_type=covariance_type, random_state=random_state).fit(embeddings)
        labels = gmm.predict(embeddings)
        return list(labels.tolist())
