"""E8a — 2-D scatter of DINOv2 style-head embeddings coloured by HDBSCAN clusters.

Reads the cluster HTML generated by the benchmark runner for the
dinov2_graffiti_style_head + identity + HDBSCAN (mcs=5) run in exp08a.
Produces e8a_hdbscan_3clusters.pdf.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from _style import EXP_DIR, PALETTE, save, setup


def _parse_cluster_html(path: Path) -> pd.DataFrame:
    content = path.read_text()
    idx = content.index("const spec = ") + len("const spec = ")
    depth, in_str, esc, i = 0, False, False, idx
    while i < len(content):
        c = content[i]
        if esc:
            esc = False
        elif c == "\\" and in_str:
            esc = True
        elif c == '"':
            in_str = not in_str
        elif not in_str:
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    break
        i += 1
    spec = json.loads(content[idx : i + 1])
    return pd.DataFrame(spec["data"]["values"])


def _find_cluster_html(exp: str, run_id: str) -> Path:
    out = EXP_DIR / exp / "output"
    matches = list(out.glob(f"*{run_id}*_cluster.html"))
    if not matches:
        raise FileNotFoundError(f"no cluster HTML for run {run_id} in {out}")
    return matches[0]


def _pick_run_id(exp: str) -> str:
    """Return run_id of dinov2_graffiti_style_head + identity + HDBSCAN mcs=5."""
    out = EXP_DIR / exp / "output"
    jsons = sorted(out.glob("benchmark_*.json"))
    with jsons[-1].open() as f:
        results = json.load(f)["results"]
    for r in results:
        params = r.get("clustering_params", "{}")
        if isinstance(params, str):
            params = json.loads(params)
        if (
            r.get("embedding_type") == "dinov2_graffiti_style_head"
            and r.get("reduction_type") == "identity"
            and "hdbscan" in r.get("clustering_type", "").lower()
            and params.get("min_cluster_size") == 5
        ):
            return r["run_id"]
    raise ValueError("target run not found in exp08a benchmark JSON")


def main() -> None:
    setup()

    run_id = _pick_run_id("exp08a")
    html = _find_cluster_html("exp08a", run_id)
    df = _parse_cluster_html(html)

    noise_mask = df["is_noise"]
    clusters = sorted(df.loc[~noise_mask, "cluster"].unique())

    fig, ax = plt.subplots(figsize=(6.0, 5.0))

    # Noise points first (grey, small, behind)
    ax.scatter(
        df.loc[noise_mask, "x"],
        df.loc[noise_mask, "y"],
        c="#cccccc",
        s=14,
        linewidths=0,
        label="ruido",
        zorder=1,
    )

    for i, cl in enumerate(clusters):
        mask = (~noise_mask) & (df["cluster"] == cl)
        ax.scatter(
            df.loc[mask, "x"],
            df.loc[mask, "y"],
            c=[PALETTE[i]],
            s=22,
            linewidths=0,
            label=f"clúster {cl}",
            zorder=2,
        )

    ax.set_xlabel("UMAP 1")
    ax.set_ylabel("UMAP 2")
    ax.set_title(
        "E8a · DINOv2 style-head — clusters HDBSCAN (mcs=5)"
    )
    ax.legend(loc="best", markerscale=1.4)
    ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)
    ax.set_aspect("equal", adjustable="datalim")

    save(fig, "e8a_hdbscan_3clusters")


if __name__ == "__main__":
    main()
